### ISSUE TITLE
[Login popup] The user closes Login popup by clicking outside of this popup

### ISSUE THREAD

**Issue by online-marathon** [Space2Study-UA-1125/frontEnd#79]
**Environment**: Windows10 21H2, Chrome 112.0.5615.138
**Reproducible**: always

**Preconditions**

The user enters Login popup window by clicking Login button  in the upper right corner of the header

**Steps to reproduce**

Click outside of the Login popup

**Actual result**

Login popup window closes

**Expected result**

Nothing should happen

**Comment by iaremchuk** [comment]
Login popup window does not close when clicking outside the modal, because the Material-UI Dialog component is used in this case. Dialog is a type of [modal] window that appears in front of app content to provide critical information or ask for a decision. Dialogs disable all app functionality when they appear, and remain on screen until confirmed, dismissed, or a required action has been taken. Therefore no changes in code required.

More about Material-UI Dialog component: https://mui.com/material-ui/react-dialog/
The logic of loginButton:
const openLoginDialog = useCallback(() => {
    openModal({ component: <LoginDialog /> })
  }, [openModal])
 return (
    <Box sx={styles.iconBox}>
      {icons}
      <AppButton
        onClick={openLoginDialog}
        size={'medium'}
        sx={styles.loginButton}
      >
        {t('header.loginButton')}
      </AppButton>
    </Box>)
